Properly quote variables and fix operator precedence
Sadly my shell scripting is not perfect, unfortunately my tests were broken.

I may steal some style from @devinteske in the future.

diff --git a/test_patches b/test_patches
--- a/test_patches
+++ b/test_patches
@@ -13,7 +13,7 @@ fi
 WRKDIR=`pwd`
 
 NEWDIR=APPLIES
-[ -n $REGEN_PATCHES ] && NEWDIR=REGEN
+[ -n "$REGEN_PATCHES" ] && NEWDIR=REGEN
 
 mkdir -p /tmp/buildlogs
 find ${SRCDIR}/patches/RESEARCH -name $NAME | {
@@ -31,7 +31,10 @@ find ${SRCDIR}/patches/RESEARCH -name $NAME | {
         cd ${PERL_BASE}
 
         echo Applying $patch
-        patch -Ep0 -F 10 -Ni "$patch" >$log 2>&1 || continue
+        if ! patch -Ep0 -F 10 -Ni "$patch" >$log 2>&1; then
+            echo "Failed"
+            continue
+        fi
 
         new_patch=`echo "$patch" | sed -e "s/RESEARCH/$NEWDIR/"`
         new_dir=`dirname "$new_patch"`
@@ -44,7 +47,7 @@ find ${SRCDIR}/patches/RESEARCH -name $NAME | {
             done
         ) > "${new_patch}.new"
 
-        if [ -n $NO_BSD_WRAPPER ]; then
+        if [ -n "$NO_BSD_WRAPPER" ]; then
             echo Configuring
             sh ./Configure -de 2>&1 | tee -a $log
 
@@ -54,7 +57,7 @@ find ${SRCDIR}/patches/RESEARCH -name $NAME | {
             echo Testing
             make test 2>&1 | tee -a $log
 
-        elif [ -z $REGEN_PATCHES ]; then
+        elif [ -z "$REGEN_PATCHES" ]; then
             echo Copying local files
             cp -Rf ${SRCDIR}/files/* ./
 
